### ISSUE TITLE
How to find the bot

### ISSUE THREAD

**Issue by turian** [parallelo3301/zulip-chatgpt-bot#1]
I followed the instructions and am running the bot from my local laptop. I have the bot created and active, and edited .env and .zuliprc

I start it and it says:

```
(env) bash-3.2$ python3 bot.py
INFO:root:Initiate DB...
Contexts []
INFO:root:Starting the GPT Zulip bot...
```

But I can't find it on my server or @GPT it or anything

How do I begin interacting this it?

**Comment by parallelo3301** [comment]
Hey, so the steps:
1. https://github.com/parallelo3301/zulip-chatgpt-bot/blob/master/.env-example#L3
2. When you edit/create the Generic bot, the Full name should be the same value (but I have not tested it with spaces in name, etc.) 
<img width="256" alt="obrazek" src="https://user-images.githubusercontent.com/3234524/232692389-87e0a91a-0fda-4a7e-936d-7fbb06e263dd.png">
3. Bot doesn't show up in users <img width="241" alt="obrazek" src="https://user-images.githubusercontent.com/3234524/232693025-0fd3d56a-0350-4b08-b46e-3e26029ff2dd.png">
4. So you have to

a) contact him through the private message
<img width="173" alt="obrazek" src="https://user-images.githubusercontent.com/3234524/232693312-e9fb434b-68a3-495c-90df-b6e593090869.png">

b) really **mention** him (so there will be `@**GPT**` in the message source, not just `@GPT`. You can verify proper  mention by that you are able to click on the mention to open the person/bot details after the message is sent.


---

There might be two issues which I didn't have to solve yet.
1. The mention format looks a little bit different if there is some duplication. What Zulip then does is having the user id appended to the mention, so the mention source format looks like `@**GPT|10**`, where 10 is that user id. The regex in this project doesn't count with this situation.
2. It was not tested with Zulip Cloud. I'm using the self-hosted solution, so there might be some differences in usage that I'm not aware of.

Let me know how it goes.

**Comment by turian** [comment]
@parallelo3301 So I'm trying the bot on a 1-click installed version of Zulip on Digital Ocean.

In that machine, as root, I clone your repo and follow the instructions. I can find the bot and message it but it doesn't respond.

1) Can you add some diagnostics or logging just to demonstrate it has received a message?
2) Is key in .zuliprc the OPENAI_API key? If not, how to find the right key?

**Comment by turian** [comment]
Okay so I think the key in .zuliprc (step 2 above) should be the bot's key when you click on it in Zulip.

However, it still won't respond.

I just get
```
~/zulip-chatgpt-bot# python3 bot.py
INFO:root:Initiate DB...
Contexts []
INFO:root:Starting the GPT Zulip bot...
```

It is possible to check the keys upon startup?
Is there more logging that can help diagnose the issue?

**Comment by parallelo3301** [comment]
I have added more logs to help you identify the issue.
You can pull new changes, and [add this line](https://github.com/parallelo3301/zulip-chatgpt-bot/blob/master/.env-example#L4) to your `.env` file.
```
LOGLEVEL="DEBUG"
```

**Comment by turian** [comment]
@parallelo3301 Okay I tried it

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): chat.movefastcrew.com:443
DEBUG:urllib3.connectionpool:https://chat.mydomain.com:443 "GET /api/v1/server_settings HTTP/1.1" 200 None
INFO:root:Initiate DB...
INFO:root:Contexts
INFO:root:[]
DEBUG:urllib3.connectionpool:https://chat.mydomain.com:443 "GET /api/v1/users/me HTTP/1.1" 401 65
DEBUG:root:{'result': 'error', 'msg': 'Invalid API key', 'code': 'UNAUTHORIZED'}
ERROR:root:Invalid API key

Is this the Bot API key? But I literally just went to the Bot's page https://chat.mydomain.com/#settings/your-bots and got the key from there

**Comment by turian** [comment]
I also tried my API key from https://chat.mydomain.com/#settings/account-and-privacy and that didn't work either in the .zuliprc

**Comment by parallelo3301** [comment]
Go to Zulip bots, and copy/download `.zuliprc` (second icon for download, third to copy the file content).
<img width="224" alt="obrazek" src="https://user-images.githubusercontent.com/3234524/234853036-75145352-742a-4f62-aa13-6046c0414a07.png">

**Comment by turian** [comment]
@parallelo3301 Wow this is great! That worked. Perhaps a brief doc update?
